### PR TITLE
substitute old savefig code with PlotlyKaleido

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
Well, it doesn't hang on precompilation, but errors at using time

**Comment by thchr** [comment]
For extensions that pull in PlotlyJS.jl, this seems to be essentially an equivalent problem though?

**Comment by BeastyBlacksmith** [comment]
In that it doesn't work on windows, yes.

**Comment by disberd** [comment]
@BeastyBlacksmith, is there a reason why this PR didn't use `savefig` directly from PlotlyKaleido instead of basically reimplementing the same method?

I had a quick look at the code here and didn't see too much difference

**Comment by BeastyBlacksmith** [comment]
> though it's a pity to have the duplication

Yeah, they differed slightly, so I didn't want to touch it. But if you have a way to streamline that, feel free to go for it.

**Pull request merged**
