### PR TITLE
Generate artifacts using gh-actions

### LINKED ISSUE #369: plotly-latest.min.js from artifact not working
**Describe the bug**
When rendering a plotlyJS plot in html, it will fetch `plotly-latest.min.js`, which has nonsensical content (see image)
This is also what I see when I download and expand [the artifact](https://github.com/thomasjm/PlotlyJS.jl/releases/download/v0.14/plotly.js-artifacts-1.57.1.tar.gz) manually.
It might be that it is GZIP'ed, and the server that serves it is supposed to figure that out?
I'm implementing WebIO in Pluto.jl, didn't test it on Jupyter or anything, but my code worked perfectly before yesterdays release (and switching to v0.14.0 now solves it)

image
(This image is more huge than I intended it to be)

**`versioninfo()`**
```
Julia Version 1.6.0-rc1
Commit a58bdd9010 (2021-02-06 15:49 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake-avx512)
Environment:
  JULIA_PATH = /usr/local/julia
  JULIA_GPG = 3673DF529D9049477F76B37566E3C7DC03D6E495
  JULIA_VERSION = 1.6.0-rc1
  JULIA_REVISE_WORKER_ONLY = 1
```

**`pkg"status"`**
```
[97c1335a] JSExpr v0.5.2
[f0f68f2c] PlotlyJS v0.14.1
[0f1e0344] WebIO v0.8.15
```

### PR DESCRIPTION
**Pull request by jonas-kr**
This pull request comprises the generation of the plotly-artifacts using GitHub Actions. We can (for now) manually run the action "artifacts" to update (or generate) the tarball "plotly-artifacts.tar.gz" which is available as a release. The Artifacts.toml file is then updated automatically.

As a side effect, this pull request resolves #369 and #370 .

Please feel free to propose further changes!  👍 

EDIT: Unfortunately, the Documenter workflow is currently broken since the update of the hash in the file Artifact.toml happens in a separate commit.

### CODE REVIEW

**Comment by sglyon** [comment]
Hi @jonas-kr I've recieved some reports that this branch is helpful in getting things working properly on all systems.

I see that it is still labeled as a draft. Do you recall if this is ready to be reviewed, or should I wait a little longer to resolve any outstanding draft issues?


Thank you!

**Comment by jonas-kr** [comment]
Hi @sglyon, 

while this branch indeed does work, the included fix is a bit problematic: Each time the plotly-artifact is built and added to the release list, it has a different checksum. Hence, I made sure that building the artifact with GH actions automatically modifies the `Artifacts.toml`. However, this modification leads to the documenter building action expecting a different checksum as it does not take the updated `Artifacts.toml` into account.

Do you have an idea on how to circumvent this problem? I already thought about adding the required artifacts to Yggdrasil which would simplify things quite a bit...

Best, Jonas

**Comment by jonas-kr** [comment]
@sglyon Finally, an update. Since the artifact does not run manually anymore, you might be able to merge this PR? The Documenter will probably still fail on the first run; however, after triggering the artifact workflow once, subsequent Documenter runs should work just fine. 
If you do not mind, you could merge #378 after the artifact workflow has finished. This way, any issues with the Documenter workflow would show up immediately.

**Comment by MichaelHatherly** [comment]
> Each time the plotly-artifact is built and added to the release list, it has a different checksum.

When a new artifact is built does this just replace the current artifact at `https://github.com/JuliaPlots/PlotlyJS.jl/releases/download/plotly-artifacts/plotly-artifacts.tar.gz` with a new version with different contents? If so then will this not fail if someone requires a specific earlier version that still points to the fixed `plotly-artifacts` URL, but does not contain the older artifact? I'd assume these artifact releases need to be versioned for the sake of reproducibility?

**Comment by jonas-kr** [comment]
@MichaelHatherly what you describe is exactly what happens each time a new artifact is built. It would be ideal to have the artifacts named according to the corresponding plotly release. Otherwise the versioning might be a bit opaque. However, I have no idea how this procedure could be implemented automatically.

**Comment by MichaelHatherly** [comment]
Or point the CDN url at a specific version rather than `latest` (`https://cdn.plot.ly/plotly-$(version).min.js`), and include that version in the artifact URL, that way it requires a little bit of manual intervention to update to the newest version of plotly, but the artifact generation itself is automatic. When a new version comes out all that's required then is bumping the `version` and the rest is taken care of.

**Comment by jonas-kr** [comment]
@MichaelHatherly Thanks a lot for your suggestions. I went with the second version: Now, the plotly version is defined in the Github Action for artifact generation. Everything else happens automatically.

**Comment by jonas-kr** [comment]
One more change: Now, the Github action passes the current repository to the `generate_artifacts` function. This way, building artifacts should work on every fork without further changes to the code.

**Comment by thchr** [comment]
I don't think I follow all the details in this PR - but from a practical perspective, this repo has been broken for me for 2+ months. If this is the case for everyone, it would seem really nice if this PR could merged soon (and a new release tagged)?

(@jonas-kr's branch has been working perfectly in the meantime - thanks! - I'm just getting tired of updating Project.toml's across different projects to fix this and of directing collaborators to hard-to-find branches)

**Comment by MichaelHatherly** [comment]
Agreed, it would be great to get this merged and tagged.

**Comment by jonas-kr** [comment]
We have to run the new artifact generating action once after merging, otherwise this PR will yield a broken repo!

**Comment by sglyon** [comment]
Just merged!! Also ran the action manually.

@jonas-kr are we good to go now?

**Comment by jonas-kr** [comment]
@sglyon Thanks a lot! The new release works just fine.

**Pull request merged**
